global using Xunit;
global using Domain.Entities;
global using Infrastructure.Data;
global using Infrastructure.Repository;
global using Microsoft.EntityFrameworkCore;
global using Application.Services;
global using Domain.IRepository;
global using Microsoft.Extensions.Logging;
global using Moq;